openapi: 3.0.0
info:
  title: Products API
  version: 1.0.5
  description: A simple API for managing medical products

paths:
  /products:
    get:
      operationId: listProducts
      summary: List all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      operationId: createProduct
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      operationId: getProductById
      summary: Get product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - category
        - status
      properties:
        id:
          type: string
          example: "MED-123"
        name:
          type: string
          example: "Paracetamol 500mg"
        category:
          type: string
          enum: [MEDICATION, DEVICE, SUPPLY]
          example: "MEDICATION"
        status:
          type: string
          enum: [AVAILABLE, OUT_OF_STOCK, DISCONTINUED]
          example: "AVAILABLE"
        description:
          type: string
          example: "Pain relief medication"
        manufacturer:
          type: string
          example: "PharmaCorp Ltd"
        expiryDate:
          type: string
          format: date
          example: "2025-12-31"
