# GitHub Actions workflow to deploy OpenAPI specs to Azure API Management and enable mocking

name: Deploy OpenAPI to Azure APIM with Mocking

on:
  push:
    paths:
      - 'sample-apis/*.yaml'
      - '.github/workflows/deploy-apim-mock.yaml'
    branches:
      - main

jobs:
  deploy-apim-mock:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy OpenAPI spec to APIM and enable mocking
        env:
          AZURE_APIM_RESOURCE_GROUP: ${{ secrets.AZURE_APIM_RESOURCE_GROUP }}
          AZURE_APIM_SERVICE_NAME: ${{ secrets.AZURE_APIM_SERVICE_NAME }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          export AZURE_TOKEN=$(az account get-access-token --query accessToken -o tsv)
          for api_file in sample-apis/*.yaml; do
            api_name=$(basename "$api_file" .yaml)
            api_path="$api_name"
            openapi_content=$(python3 -c "import sys, yaml, json; def default(o): return str(o); print(json.dumps(yaml.safe_load(sys.stdin), default=default))" < "$api_file")
            echo "Importing $api_file as $api_name to APIM via REST API..."
            curl -X POST \
              -H "Authorization: Bearer $AZURE_TOKEN" \
              -H "Content-Type: application/json" \
              "https://management.azure.com/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_APIM_RESOURCE_GROUP/providers/Microsoft.ApiManagement/service/$AZURE_APIM_SERVICE_NAME/importOpenApi?api-version=2024-05-01" \
              -d "{\"properties\":{\"format\":\"openapi\",\"value\":$openapi_content,\"path\":\"$api_path\"}}"
            for op in listPatients getPatientById; do
              curl -X PATCH \
                -H "Authorization: Bearer $AZURE_TOKEN" \
                -H "Content-Type: application/json" \
                "https://management.azure.com/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_APIM_RESOURCE_GROUP/providers/Microsoft.ApiManagement/service/$AZURE_APIM_SERVICE_NAME/apis/$api_name/operations/$op?api-version=2024-05-01" \
                -d '{"properties":{"request":{"representations":[]},"responses":[{"representations":[{"contentType":"application/fhir+json","sample":"MOCK"}]}]}}'
            done
          done
        shell: bash

      - name: Logout from Azure
        run: az logout
