# GitHub Actions workflow to automate Terraform apply before APIM OpenAPI deployment

name: Infra and APIM Deploy Pipeline

on:
  push:
    paths:
      - 'infra/**'
      - 'sample-apis/*.yaml'
      - '.github/workflows/infra-apim-deploy.yaml'
    branches:
      - main

jobs:
  apim-deployment:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: infra
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        env:
            TF_LOG: INFO
        run: |
            terraform init \
            -backend-config="resource_group_name=${{ secrets.AZURE_APIM_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Apply
        env:
            TF_LOG: INFO
        run: |
          terraform destroy -auto-approve \
            -var="apim_name=${{ secrets.AZURE_APIM_SERVICE_NAME }}" \
            -var="resource_group_name=${{ secrets.AZURE_APIM_RESOURCE_GROUP }}" \
            -var="location=${{ secrets.AZURE_LOCATION }}"
